// Console.WriteLine("Привет от ИСП-241!");
// Console.WriteLine("Автор: Иванова Анфиса");
// Console.WriteLine("Год: 2026");
// int age = 20;
// double gpa = 4.5;
// bool isStudent = true;
// string name = "Иван";
// Console.WriteLine(name);
// Console.WriteLine(age);
// Console.WriteLine(gpa);
// Console.WriteLine(isStudent);
// var city = "Москва";
// var year = 2026;
// var pi = 3.14159;
// var isActive = true;
// string myName = "Анфиса";
// int myAge = 19;
// string myGroup = "ИСП-241";
// Console.WriteLine($"Меня зовут {myName}, мне {myAge} лет, я учусь в группе {myGroup}.");
// Console.Write("Введите ваше имя: ");
// string name2 = Console.ReadLine();
// Console.WriteLine($"Привет, {name2}!");
// Console.Write("Введите ваш возраст: ");
// string input = Console.ReadLine();
// int age2 = int.Parse(input);
// Console.WriteLine($"Через 10 лет вам будет {age2 + 10} лет.");
// int x = 10;
// int y = 3;
// Console.WriteLine(x + y);
// Console.WriteLine(x - y);
// Console.WriteLine(x * y);
// Console.WriteLine(x / y);
// Console.WriteLine(x % y);
// string firstName = "Анфиса";
// string lastName = "Иванова";
// string group = "ИСП-241";
// int birthYear = 2007;
// double gpa = 4.5;
// bool hasScholarship = true;
// int currentYear = 2026;
// int age = currentYear - birthYear;
// Console.WriteLine("Студенческое удостоверение");
// Console.WriteLine($"Имя: {firstName} {lastName}");
// Console.WriteLine($"Группа: {group}");
// Console.WriteLine($"Возраст: {age} лет");
// Console.WriteLine($"Средний балл: {gpa}");
// Console.WriteLine($"Стипендия: {hasScholarship}");
// Console.Write("\nВведите ваш любимый предмет: ");
// string subject = Console.ReadLine();
// Console.WriteLine($"Отлично! {firstName} любит {subject}.");
// int a = 15;
// int b = 4;
// Console.WriteLine($"Сумма: {a + b}");
// Console.WriteLine($"Разность: {a - b}");
// Console.WriteLine($"Произведение: {a * b}");
// Console.WriteLine($"Частное (int): {a / b}");
// Console.WriteLine($"Остаток: {a % b}");
// double result = (double)a / b;
// Console.WriteLine($"Частное (double): {result}");
// Console.WriteLine(Math.Abs(-5));
// Console.WriteLine(Math.Pow(2, 10));
// Console.WriteLine(Math.Sqrt(144));
// Console.WriteLine(Math.Max(10, 25));
// Console.WriteLine(Math.Min(10, 25));
// Console.WriteLine(Math.Round(3.567, 2));
// Console.WriteLine("Калькулятор");
// Console.Write("Введите первое число: ");
// double num1 = double.Parse(Console.ReadLine());
// Console.WriteLine(int.MaxValue);
// Console.WriteLine(int.MinValue);
// Console.WriteLine(double.MaxValue);
// Console.WriteLine(double.MinValue);
// Console.WriteLine("Введите ваше имя: ");
// string name = Console.ReadLine();
// Console.WriteLine("Введите вашу фамилию: ");
// string surname = Console.ReadLine();
// Console.WriteLine("Введите вашу группу: ");
// string group = Console.ReadLine();
// Console.WriteLine("Введите ваш год рождения: ");
// int birthYear = int.Parse(Console.ReadLine());
// Console.WriteLine("Введите ваш средний балл (например, 4.5): ");
// double gpa = double.Parse(Console.ReadLine());

// int currentYear = 2026;
// int age = currentYear - birthYear;
// bool isExcellent = gpa >= 4.5;

// string status;
// if (isExcellent == true)
//     status = "Отличник";
// else
//     status = "Хорошист";
// Console.WriteLine("Ваша анкета");
// Console.WriteLine($"Имя: {name} {surname}");
// Console.WriteLine($"Группа: {group}");
// Console.WriteLine($"Возраст: {age} лет");
// Console.WriteLine($"Средний балл: {gpa}");
// Console.WriteLine($"Лет до 30: {30 - age}");
// Console.WriteLine("Нажмите Enter для выхода...");
// Console.ReadLine();
string film = "Голодные игры";
int n = 6;
double pii = 3.14;
string a = "A";
Console.WriteLine($"Любимая игра: {film}");
Console.WriteLine($"Любимая цифра: {n}");
Console.WriteLine($"Число пи: {pii}");
Console.WriteLine($"Любимая буква: {a}");
Console.WriteLine("I");
Console.WriteLine("need");
Console.WriteLine("more");
Console.WriteLine("power!");
Console.WriteLine("Hello There");
Console.WriteLine("Введите стоимость монитора: ");
int n1 = int.Parse(Console.ReadLine());
Console.WriteLine("Введите стоимость системного блока: ");
int n2 = int.Parse(Console.ReadLine());
Console.WriteLine("Введите стоимость клавиатуры: ");
int n3 = int.Parse(Console.ReadLine());
Console.WriteLine("Введите стоимость мыши: ");
int n4 = int.Parse(Console.ReadLine());
int N = (n1 + n2 + n3 + n4) * 3;
Console.WriteLine($"Стоимость трех компьютеров: {N}");
Console.WriteLine("Введите число a: ");
int A = int.Parse(Console.ReadLine());
Console.WriteLine("Введите число b: ");
int b = int.Parse(Console.ReadLine());
double s = 3 * Math.Pow(A + b, 3) + 275 * Math.Pow(b, 2) - 127 * A - 41;
Console.WriteLine($"Значение функции: {s}");
double C = double.Parse(Console.ReadLine());
double F = C * 9.0 / 5.0 + 32;
Console.WriteLine($"Температура: {F}°F");